name: expense_capture
description: Capture all you expenses from the reciept.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  edge_detection: ^1.0.9
  google_mlkit_text_recognition: ^0.4.0
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher_adaptive.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/ic_launcher_adaptive.png"
    background_color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ic_launcher_adaptive.png
